sm6150-common: fingerprint: Add on show|hide udfps overlays
Without this, build will throw error below:

device/xiaomi/sm6150-common/fingerprint/BiometricsFingerprint.cpp:276:25: error: allocating an object of abstract class type 'android::hardware::biometrics::fingerprint::V2_3::implementation::BiometricsFingerprint'
        sInstance = new BiometricsFingerprint();
                        ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:214:47: note: unimplemented pure virtual method 'onShowUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onShowUdfpsOverlay() = 0;
                                              ^
out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.3/android.hardware.biometrics.fingerprint@2.3_genc++_headers/gen/android/hardware/biometrics/fingerprint/2.3/IBiometricsFingerprint.h:219:47: note: unimplemented pure virtual method 'onHideUdfpsOverlay' in 'BiometricsFingerprint'
    virtual ::android::hardware::Return<void> onHideUdfpsOverlay() = 0;
                                              ^
since we don't use it, for now let's just satisfy it with blank callbacks.

Co-Authored-By: magicxavi <rolfpeterkesche@gmail.com>
Co-Authored-By: SagarMakhar <25933684+SagarMakhar@users.noreply.github.com>